repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check
        language: system
        types: [python]
        args: [ --fix ]

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: python3 -m pylint.__main__
        language: system
        types: [python]
        require_serial: true
