[project]
name = "ai-agent-using-gemini"
version = "0.1.0"
description = "Add your description here"
authors = [
    {name = "Nhat Tai NGUYEN",email = "nhattai.nguyen88@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12, <4.0"
dependencies = [
    "google-genai==1.12.1",
    "python-dotenv==1.1.0",
]

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "pre-commit>=4.6.0",
    "pylint>=4.0.5",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.12",
]
